package com.miles.maipu.net;

public enum ApiCode
{
	iploadimg,
	login,
	GetAllPersonOfSameDepart,
	GetOrganization,
	GetRoadLinesByPersonID,
	Signin,
	GetAllPatorlCateGoryAndItems,
	GetPatorlRecordDetailList,
	GetPatorlRecordDetail,
	GetPatorlRecordDetailByRecordID,
	UpdatePatorlRecordDetail,
	GetAllPatorlCateGory,
	GetPatorlItemsByCateGoryID,
	AddPatorlRecordDetail,
	GetEventsByPersonID,
	GetEventAllot,
	AddEventFeedback,
	AddEventAllot,
	GetEventAllotDetails,
	GetEventSubmitsNoAlloted,
	GetEventSubmitToAlloted,
	GetEventReceiveToAlloted,
	SaveFile, 
	geteventsubmit,
	GetOrganizationUpOrDown, 
	GetPersonInformationByOrganization, 
	AddEventSubmit, 
	GetSubmitEvent, 
	GetSubordinate,
	GetPatrolNavigationPoint,
	PostLicenseInfoByItemAndNum,
	GetLicenseInfoForPN, GetLicenseInfoByItemAndNum, GetAllUsedApplicationItem, GetNoticesByPersonID,GetNoticeByID, getallLawForApp, GetLawByPatorlItemID,
	AuditEventAllot, GetHandleNumByPersonID, GetPatorlRecordDetailListByOrgID, GetEventsByOrgID, GetAllPatorlRecordDetailByPersonID, GetAllPatorlCars, GetSignRoadLineByPersonID, SaveTrajectory, 
}
